name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Verify installations
      run: |
        python -c "import flask; print('✓ Flask installed')"
        python -c "import flask_sqlalchemy; print('✓ Flask-SQLAlchemy installed')"
        python -c "import flask_migrate; print('✓ Flask-Migrate installed')"
        python -c "import xlsxwriter; print('✓ XlsxWriter installed')"
        python -c "import numpy; print(f'✓ NumPy {numpy.__version__} installed')"
        python -c "import pandas; print(f'✓ Pandas {pandas.__version__} installed')"

    - name: Run basic syntax check
      run: |
        python -m py_compile app.py
        python -m py_compile manage.py
        python -m py_compile config.py
        echo "✓ Basic syntax check passed"

  deploy:
    runs-on: windows-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Display deployment info
      run: |
        echo "Deployment successful!"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"